/**
 * AUTO-GENERATED by scripts/generate-gallery-data.js
 * Do not edit manually — re-run the script after adding/removing photos.
 */
import type { GalleryImage } from "../components/LightboxGallery";

export const barbershopImages: GalleryImage[] = [
  { src: "/babershop/0-02-05-0f1d4430987be2e01db20583e763736af22b9d2a6241c3b97cac2423735c86d0_6cb389b92b1f89e5.jpg", alt: "Kingdom Place barbershop" },
  { src: "/babershop/0-02-05-c4d76e5cf5bb01c652c6818203773ce13a6972cc57f3dbd9269fa407b0e8c27a_628fcd96256b0928.jpg", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277592.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277593.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277595.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277596.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277597.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277598.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/277599.webp", alt: "Kingdom Place barbershop" },
  { src: "/babershop/photo-1621605815971-fbc98d665033.jpg", alt: "Kingdom Place barbershop" },
];

export const alayoubiGallery: GalleryImage[] = [
  { src: "/barbers/Alayoubi/0-02-05-089b7d331b5f9417466160f675edd6a7b9aa679039be405adc3cfa4b57d0caff_9a62d5468bc3eed8.jpg", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/0-02-05-2ac8aa5b335301a80db4ac29ba7915104b578b1820fa6967530fe8f93a24e6f6_466c23a5b7e6f077.jpg", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/0-02-05-2f6f84336230d810206fac7eb744f2133a3fef4f39ed14d72f104cb16f0e1fa5_ae7e68a18081bd2e.jpg", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/0-02-05-da005ad25859b91e5883288784c8f61194661ccc1b09c9ae2a8ebe42c321d6f3_c2666b6fd03aeb09.jpg", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1773850861.webp", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1773850870.webp", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1773850876.webp", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1774447890.webp", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1774601139.webp", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1774601151.webp", alt: "Alayoubi — Barber work" },
  { src: "/barbers/Alayoubi/1774639467.webp", alt: "Alayoubi — Barber work" },
];

export const alayoubiBeforeAfter: { before: GalleryImage; after: GalleryImage }[] = [
  {
    before: { src: "/barbers/Alayoubi/before-02.jpg", alt: "Alayoubi — Before" },
    after: { src: "/barbers/Alayoubi/after-02.jpg", alt: "Alayoubi — After" },
  },
];

export const khalilGallery: GalleryImage[] = [
  { src: "/barbers/Khalil/0-02-05-7992b5bfcea167710823978b7146c2c5ef096c410084bbccc435416501fd3832_5dcaedb3f2d6d53a.jpg", alt: "Khalil — Barber work" },
  { src: "/barbers/Khalil/photo-1503951914875-452162b0f3f1.jpg", alt: "Khalil — Barber work" },
  { src: "/barbers/Khalil/photo-1599351431202-1e0f0137899a.jpg", alt: "Khalil — Barber work" },
];

export const khalilBeforeAfter: { before: GalleryImage; after: GalleryImage }[] = [
];

export const barberGalleryMap: Record<string, GalleryImage[]> = {
  alayoubi: alayoubiGallery,
  khalil: khalilGallery,
};

export const beforeAfterMap: Record<string, { before: GalleryImage; after: GalleryImage }[]> = {
  alayoubi: alayoubiBeforeAfter,
  khalil: khalilBeforeAfter,
};
